# PolyVore OCIR data nums: 16995

includes:
- configs/models/csa_net/defaults.yaml
# - configs/datasets/polyvore_ocir/nondisjoint.yaml

model_config:
  csa_net:
    losses:
    - type: contrastive_loss

    image_channel: 512
    n_categories: 153
    n_conditions: 5
    feature_dim: 256

    image_encoder:
      image_encoder:
      type: clip_image_encoder
      params:
        name: ViT-B/16
        freeze: true
        adapter_name: adaptformer
        bottleneck: 64
        dropout: 0

dataset_config:
  polyvore_ocir:
    processors:
      train_image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: RandomResizedCrop
              params:
                size: [224, 224]
                scale: [0.8, 1.0]
                ratio: [0.75, 1.3]
            - RandomHorizontalFlip
            - ToTensor
            - type: Normalize
              params:
                mean: [0.48145466, 0.4578275, 0.40821073]
                std: [0.26862954, 0.26130258, 0.27577711]
      eval_image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [224, 224]
            - ToTensor
            - type: Normalize
              params:
                mean: [0.48145466, 0.4578275, 0.40821073]
                std: [0.26862954, 0.26130258, 0.27577711]

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 1500
    - 5000
    lr_ratio: 0.1
    warmup_iterations: 1000
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-4
    eps: 1e-8
    weight_decay: 0.0

evaluation:
  metrics:
  - r@k_ocir

training:
  experiment_name: polyvore_csa_disjoint_clip_adaptformer
  batch_size: 64
  lr_scheduler: true
  max_updates: 8000
  log_interval: 10
  checkpoint_interval: 8000
  evaluation_interval: 500
  early_stop:
    criteria: polyvore_ocir/r@k_ocir/avg
    minimize: false
  wandb:
    enabled: true

run_type: train_val
