# PolyVore OCIR data nums: 16995

includes:
- configs/models/csa_net/defaults.yaml
# - configs/datasets/polyvore_ocir/nondisjoint.yaml

model_config:
  csa_net:
    losses:
    - type: contrastive_loss

    image_channel: 2048
    n_categories: 153
    n_conditions: 5
    feature_dim: 64

    image_encoder:
      type: torchvision_resnet
      params:
        name: resnet50
        pretrained: true
        zero_init_residual: false
        num_output_features: 1
        pool_type: avg

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 0
    num_training_steps: ${training.max_updates}

optimizer:
  type: Adam
  params:
    lr: 5e-5
    eps: 1e-8
    weight_decay: 1e-4

evaluation:
  metrics:
  - r@k_ocir

training:
  experiment_name: polyvore_csa_disjoint
  batch_size: 32
  lr_scheduler: true
  max_updates: 8000
  log_interval: 10
  checkpoint_interval: 8000
  evaluation_interval: 500
  early_stop:
    criteria: polyvore_ocir/r@k_ocir/avg
    minimize: false
  wandb:
    enabled: true

run_type: train_val

checkpoint:
  resume_pretrained: true
  resume_file: save/fashionvil_e2e_pretrain_baseline/best.ckpt
  pretrained_state_mapping:
    image_encoder: image_encoder
