# FashionGen data nums: 60147

includes:
- ./fashiongen_cap_dataset_cfg.yaml

model_config:
  fashionclip:
    training_head_type: mtl
    clip_config:
      clip_model_name: openai/clip-vit-base-patch16
    adapter_config:
      freeze: false
      adapter_name: scaled_pa
      bottleneck: 64
      dropout: 0.0
      enable_xattn: true
      only_textual_xattn: true
      share_cross: false
      share_adapter: false
      cross_dropout: 0.0
    lr_multiplier: 100
    tasks:
    - cap
    decoding_algorithm: beam

scheduler:
  type: multi_step
  params:
    use_warmup: false
    lr_steps:
    - 20000
    lr_ratio: 0.1
    warmup_iterations: 2810
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-6
    eps: 1e-8
    weight_decay: 1e-5

evaluation:
  metrics:
    - bleu4
    - rougel
    - meteor

training:
  experiment_name: fashionclip_fashiongen_cap_alltrain
  batch_size: 64
  lr_scheduler: true
  max_updates: 30000
  log_interval: 10
  checkpoint_interval: 1000
  evaluation_interval: 1000
  find_unused_parameters: true
  early_stop:
    criteria: fashiongen_cls/bleu4
    minimize: false
  wandb:
    enabled: true

run_type: train_val
