# FashionIQ data nums: 18000
# FashionGen data nums: 60147

includes:
- ./fashioniq_dataset_cfg.yaml
- ./fashiongen_dataset_cfg.yaml
- ./fashiongen_cls_dataset_cfg.yaml

model_config:
  fashionclip:
    training_head_type: mtl
    clip_config:
      clip_model_name: openai/clip-vit-base-patch16
    tasks:
    - itc
    - tgir
    - scr
    num_labels: 121

scheduler:
  type: multi_step
  params:
    use_warmup: false
    lr_steps:
    - 40000
    lr_ratio: 0.1
    warmup_iterations: 2810
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-6
    eps: 1e-8
    weight_decay: 1e-5

evaluation:
  metrics:
  - type: r@k_fashioniq
    datasets:
    - fashioniq
  - type: r@k_general
    datasets:
    - fashiongen
  - type: accuracy
    datasets:
    - fashiongen_cls
  - type: macro_f1
    datasets:
    - fashiongen_cls

training:
  experiment_name: fashionclip_mtl(itc+tgir+scr)
  batch_size: 64
  lr_scheduler: true
  max_updates: 60000
  log_interval: 10
  checkpoint_interval: 1000
  evaluation_interval: 1000
  find_unused_parameters: true
  early_stop:
    criteria: fashioniq/r@k_fashioniq/avg
    minimize: false
  wandb:
    enabled: true

run_type: train_val

multitasking:
  enabled: true
  type: size_proportional
