# FashionGen data nums: 60147

includes:
- configs/models/alignment/clip.yaml

model_config:
  simple_alignment:
    final_hidden_size: 512
    direct_features_input: false
    lr_multiplier: 20
    text_encoder:
      type: transformer
      params:
        bert_model_name: bert-base-uncased
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false
    image_projection:
      type: linear
      params:
        in_dim: 1024
        out_dim: ${model_config.simple_alignment.final_hidden_size}
    text_projection:
      type: linear
      params:
        in_dim: 768
        out_dim: ${model_config.simple_alignment.final_hidden_size}


dataset_config:
  fashiongen:
    processors:
      train_image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: RandomCrop
              params:
                size: [224, 224]
            - RandomHorizontalFlip
            - ToTensor
            - type: Normalize
              params:
                mean: [0.48145466, 0.4578275, 0.40821073]
                std: [0.26862954, 0.26130258, 0.27577711]
      eval_image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [224, 224]
            - ToTensor
            - type: Normalize
              params:
                mean: [0.48145466, 0.4578275, 0.40821073]
                std: [0.26862954, 0.26130258, 0.27577711]

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 28170
    - 56340
    lr_ratio: 0.1
    warmup_iterations: 939
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8
    weight_decay: 1e-4

evaluation:
  metrics:
  - r@k_general

training:
  experiment_name: clipres_bert_fashiongen
  batch_size: 64
  lr_scheduler: true
  max_updates: 75120
  log_interval: 10
  checkpoint_interval: 939
  evaluation_interval: 939
  early_stop:
    criteria: fashiongen/r@k_general/avg
    minimize: false
  wandb:
    enabled: true

run_type: train_vall
